<?php

require_once "helpers/start.php";
startApp();

use PHPUnit_Framework_TestCase as PHPunit;


class PHPNativeElements extends PHPunit
{


    public function setUp()
    {

    }

    public function testCreateUser()
    {

        $userTeste = new Users();
        $userTeste->setName('FakeName');
        $userTeste->setLogin('FakeLogin');
        $userTeste->setEmail('FakeEmail@gmail.com');
        $userTeste->setPassword('FakePass');
        $userTeste->insert();

    }

    public function testeDeleteUser()
    {
        
    }

    public function testCreatePost()
    {

        $post = new Posts();

        $post->setTitle('POST TITLE TEXT');
        $post->setSlug('post-title-text');
        $post->setContent('lorem lorem lorem lorem lorem lorem lorem lorem');
        $post->insert();

    }

    public function testeDeletePostbySlug()
    {
        $post = new Posts();
        $return = $post->findBySlug('post-title-text');
        $post->delete($return->id);

    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}