<?php

require_once "helpers/start.php";
startApp();

use PHPUnit_Framework_TestCase as PHPunit;


class PHPNativeElements extends PHPunit
{


    public function setUp()
    {

    }

    public function testCreateUser()
    {

        $userTeste = new Users();
        $userTeste->setName('FakeName');
        $userTeste->setLogin('FakeLogin');
        $userTeste->setEmail('FakeEmail@gmail.com');
        $userTeste->setPassword('FakePass');
        $userTeste->insert();

    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}